port = 8080
tailscale_socket = "/var/run/tailscale/tailscaled.sock"
<<<<<<< HEAD
=======

[[share]]
name = "documents"
path = "/shares/documents"
readonly = true

[[share]]
name = "dropzone"
path = "/shares/dropzone"
readonly = false
>>>>>>> parent of cbdda34 (config: Changed readonly in config.toml)
