package config

import (
	"fmt"
	"os"

	"github.com/BurntSushi/toml"
)

type ProtocolStyle int

const (
	ProtocolStyleCompatibility ProtocolStyle = iota
	ProtocolStyleMostCompatible
)

var styleNames = map[string]ProtocolStyle{
	"compatibility":   ProtocolStyleCompatibility,
	"most-compatible": ProtocolStyleMostCompatible,
}

func (s *ProtocolStyle) UnmarshalText(text []byte) error {
	v, ok := styleNames[string(text)]
	if !ok {
		return fmt.Errorf("invalid protocol style %s", text)
	}
	*s = v
	return nil
}

func (s ProtocolStyle) MarshalText() ([]byte, error) {
	for name, v := range styleNames {
		if v == s {
			return []byte(name), nil
		}
	}
	return nil, fmt.Errorf("invalid protocol style %d", s)
}

func (s ProtocolStyle) String() string {
	if b, err := s.MarshalText(); err == nil {
		return string(b)
	}
	return fmt.Sprintf("ProtocolStyle(%d)", int(s))
}

type Config struct {
	Port            int            `toml:"port"`
	TailscaleSocket string         `toml:"tailscale_socket"`
	Shares          []Share        `toml:"share"`
	ProtocolConfig  ProtocolConfig `toml:"protocol"`
	Fuse            FuseConfig     `toml:"fuse"`
	Sftp            SFTPConfig     `toml:"sftp"`
	Webdav          WebdavConfig   `toml:"webdav"`
}

type ProtocolConfig struct {
	AutoProtocols      *bool          `toml:"auto_protocols"`
	AutoProtocolsStyle *ProtocolStyle `toml:"auto_protocols_style"`
	AutoGenerateDelay  *uint32        `toml:"auto_generate_delay"`
	ProtocolsEnabled   []string       `toml:"protocols_enabled"`
}

type FuseConfig struct {
	Enabled    bool   `toml:"enabled"`
	Backend    string `toml:"backend"` // "sftp" or "webdav"
	Peer       string `toml:"peer"`    // tailscale hostname or IP of the remote peer
	Share      string `toml:"share"`   // remote share name
	Mountpoint string `toml:"mountpoint"`
	ReadOnly   bool   `toml:"read_only"`
}

type SFTPConfig struct {
	Port int `toml:"port"`
}

type WebdavConfig struct {
	Port int `toml:"port"`
}

func (c *Config) ApplyDefaults() {
	if c.ProtocolConfig.AutoProtocols == nil {
		c.ProtocolConfig.AutoProtocols = new(bool)
		*c.ProtocolConfig.AutoProtocols = true
	}
	if c.ProtocolConfig.AutoProtocolsStyle == nil {
		c.ProtocolConfig.AutoProtocolsStyle = new(ProtocolStyle)
		*c.ProtocolConfig.AutoProtocolsStyle = ProtocolStyleCompatibility
	}

	if c.ProtocolConfig.AutoGenerateDelay == nil {
		c.ProtocolConfig.AutoGenerateDelay = new(uint32)
		*c.ProtocolConfig.AutoGenerateDelay = 60 // 1 minute
	}

	if c.Sftp.Port == 0 {
		c.Sftp.Port = 22
	}

	if c.Webdav.Port == 0 {
		c.Webdav.Port = 8081
	}
}

func (cfg *Config) validate() error {
	for _, share := range cfg.Shares {
		if share.Name == "" {
			return fmt.Errorf("share %s has no name", share.Path)
		}

		if share.Path == "" {
			return fmt.Errorf("share %s has no path", share.Name)
		}
		if _, err := os.Stat(share.Path); err != nil {
			return fmt.Errorf("share %s path %s does not exist", share.Name, share.Path)
		}
	}
	return nil
}

func (cfg *Config) ShareMap() map[string]Share {
	m := make(map[string]Share)
	for _, share := range cfg.Shares {
		m[share.Name] = share
	}
	return m
}

type Share struct {
	Name     string `toml:"name"`
	Path     string `toml:"path"`
	ReadOnly bool   `toml:"read_only"`
}

func LoadConfig(path string) (*Config, error) {
	cfg := &Config{
		Port:            8080,
		TailscaleSocket: "/var/run/tailscale/tailscaled.sock",
	}

	if _, err := toml.DecodeFile(path, cfg); err != nil {
		return nil, err
	}

	if err := cfg.validate(); err != nil {
		return nil, err
	}

	return cfg, nil
}
