package main

import (
	"a3l6/m/webdav"
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"time"
)

func corsMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Content-Range, X-Chunk-MD5")
		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		next.ServeHTTP(w, r)
	})
}

func handleHealth(w http.ResponseWriter, r *http.Request) {
	hostname, _ := os.Hostname()
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"hostname": hostname})
}

func handleListPeers(peers []PeerShares) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(peers)
	}
}

func main() {
	taildrive_webdav.Run()

	cfg, err := loadConfig("./config.toml")
	if err != nil {
		log.Fatal(err)
		return
	}
	cfg.applyDefaults()

	localShares := cfg.ShareMap()

	peers, err := discoverPeers(context.Background(), cfg)
	if err != nil {
		fmt.Println(err)
	}

	registry.init(cfg)

	generateAvailableProtocols(peers, *cfg)

	if *cfg.ProtocolConfig.AutoProtocols {
		log.Println("protocol: auto-generating protocols")

		go func() {
			for {
				available := generateAvailableProtocols(peers, *cfg)
				log.Println("protocol: auto-generated protocols")
				autoConfigureProtocols(available, *cfg)
				log.Println("protocol: auto-configured protocols")
				time.Sleep(time.Duration(*cfg.ProtocolConfig.AutoGenerateDelay) * time.Second)
			}
		}()
	}

	mux := http.NewServeMux()
	mux.HandleFunc("GET /config", handleConfig)
	mux.HandleFunc("GET /peers", handleListPeers(peers))
	mux.HandleFunc("GET /shares", handleListShares(localShares))
	mux.HandleFunc("GET /health", handleHealth)

	ip, err := getTailscaleIP(context.Background(), cfg)
	if err != nil {
		fmt.Println(err)
		return
	}

	listener, err := net.Listen("tcp", ip+":8080")
	if err != nil {
		fmt.Println(err)
		return
	}

	log.Printf("taildrive: started listening on %s", listener.Addr().String())

	err = http.Serve(listener, corsMiddleware(mux))
	if err != nil {
		fmt.Println(err)
		return
	}
}
