package main

import (
	tdsftp "a3l6/m/sftp"
	tdvfs "a3l6/m/vfs"
	tdwebdav "a3l6/m/webdav"
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"sync"
)

type protocolConfig struct {
	AutoProtocols      *bool          `toml:"auto_protocols"`
	AutoProtocolsStyle *ProtocolStyle `toml:"auto_protocols_style"`
	AutoGenerateDelay  *uint32        `toml:"auto_generate_delay"`
	ProtocolsEnabled   []string       `toml:"protocols_enabled"`
}

type Protocol interface {
	Name() string
	Enabled() bool
	SetEnabled(bool)
	Public() map[string]any
	Run(context.Context, tdvfs.FS) error
}

type Registry struct {
	configs []Protocol

	muregistrar sync.Mutex
	registrar   map[string]context.CancelFunc
	wgregistrar sync.WaitGroup
}

func newRegistry() *Registry {
	return &Registry{
		registrar: make(map[string]context.CancelFunc),
	}
}

var registry = newRegistry()

func (r *Registry) Get(name string) Protocol {
	for _, val := range r.configs {
		if val.Name() == name {
			return val
		}
	}
	return nil
}

func (r *Registry) Start(name string, s Protocol) error {
	ctx, cancel := context.WithCancel(context.Background())

	log.Println("protocol: starting ", name, " service")

	r.muregistrar.Lock()
	if _, exists := r.registrar[name]; exists {
		r.muregistrar.Unlock()
		cancel()
		return fmt.Errorf("%s service already running", name)
	}

	r.registrar[name] = cancel
	r.muregistrar.Unlock()

	r.wgregistrar.Add(1)
	go func() {
		defer r.wgregistrar.Done()
		defer func() {
			r.muregistrar.Lock()
			delete(r.registrar, name)
			r.muregistrar.Unlock()
		}()

		if ok := r.Get(name); ok != nil {
			ok.SetEnabled(true)
		}

		if err := s.Run(ctx, filesystem); err != nil && err != context.Canceled {
			log.Printf("protocol: %s service failed: %s", name, err)
			if ok := r.Get(name); ok != nil {
				ok.SetEnabled(true)
			}
		}
	}()

	return nil

}

func (r *Registry) Stop(name string) {
	r.muregistrar.Lock()
	for _, config := range r.configs {
		if config.Name() == name {
			config.SetEnabled(false)
		}
	}

	cancel, ok := r.registrar[name]
	r.muregistrar.Unlock()
	if ok {
		cancel()
	}
}

func (r *Registry) StopAll() {
	r.muregistrar.Lock()
	for _, cancel := range r.registrar {
		cancel()
	}

	for _, config := range r.configs {
		config.SetEnabled(false)
	}
	r.muregistrar.Unlock()
	r.wgregistrar.Wait()
}

func (r *Registry) UnRegister(c Protocol) {
	for idx, val := range r.configs {
		if val.Name() == c.Name() {
			r.configs = append(r.configs[:idx], r.configs[idx+1:]...)
		}
	}
}

func (r *Registry) Register(c Protocol) { r.configs = append(r.configs, c) }

func handleConfig(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")

	out := make([]map[string]any, 0, len(registry.configs))
	for _, c := range registry.configs {
		out = append(out, map[string]any{
			"name":    c.Name(),
			"enabled": c.Enabled(),
			"public":  c.Public(),
		})
	}
	json.NewEncoder(w).Encode(map[string]any{"protocols": out})
}

func generateAvailableProtocols(peers []PeerShares, cfg Config) map[string]int {
	availableProtocols := make(map[string]int)

	for _, peer := range peers {
		resp, error := http.Get(fmt.Sprintf("http://%s:%d/config", peer.PeerIP, cfg.Port))
		if error != nil {
			log.Println("protocol: ERROR: ", error)
			continue
		}
		defer resp.Body.Close()

		var config map[string]any
		if err := json.NewDecoder(resp.Body).Decode(&config); err != nil {
			log.Println("protocol: ERROR: ", err)
			continue
		}

		for _, protocol := range config["protocols"].([]any) {
			if protocol.(map[string]any)["enabled"] == true {
				availableProtocols[protocol.(map[string]any)["name"].(string)]++
			}
		}
	}

	log.Println("protocol: found protocols:", availableProtocols)

	return availableProtocols
}

func autoConfigureProtocols(availableProtocols map[string]int, cfg Config) {
	if cfg.ProtocolConfig.AutoProtocols == nil || *cfg.ProtocolConfig.AutoProtocols == false {
		return
	}

	switch *cfg.ProtocolConfig.AutoProtocolsStyle {
	case ProtocolStyleCompatibility:
		for protocol := range availableProtocols {
			resolved := registry.Get(protocol)
			if resolved == nil {
				log.Printf("protocol: cannot find protocol %s on machine, skipping", protocol)
				continue
			}

			registry.Start(protocol, resolved)
		}
	case ProtocolStyleMostCompatible:
		var mostCompatibleProtocol string
		var bestCompatibility int

		for idx, val := range availableProtocols {
			if val > bestCompatibility {
				mostCompatibleProtocol = idx
				bestCompatibility = val
			}
		}

		resolved := registry.Get(mostCompatibleProtocol)
		if resolved == nil {
			log.Printf("protocol: cannot find protocol %s on machine, skipping", mostCompatibleProtocol)
			return
		}

		for idx := range registry.registrar {
			if idx == mostCompatibleProtocol {
				continue
			}
			registry.Stop(idx)
		}

		registry.Start(mostCompatibleProtocol, resolved)
	}
}

// File Transfer Server Wrappers

type GenericProtocolServer struct {
	name    string
	enabled bool
	public  map[string]any
	run     func(context.Context, tdvfs.FS) error
}

func (s GenericProtocolServer) Name() string           { return s.name }
func (s GenericProtocolServer) Enabled() bool          { return s.enabled }
func (s *GenericProtocolServer) SetEnabled(x bool)     { s.enabled = x }
func (s GenericProtocolServer) Public() map[string]any { return s.public }
func (s *GenericProtocolServer) Run(ctx context.Context, fs tdvfs.FS) error {
	return s.run(ctx, fs)
}

var SFTPProtocolServer GenericProtocolServer = GenericProtocolServer{
	name:    "SFTP",
	enabled: false,
	public:  make(map[string]any),
	run:     tdsftp.Run,
}

var WEBDAVProtocolServer GenericProtocolServer = GenericProtocolServer{
	name:    "WEBDAV",
	enabled: false,
	public:  make(map[string]any),
	run:     tdwebdav.Run,
}

func (r *Registry) init(cfg *Config) {
	r.Register(&SFTPProtocolServer)
	r.Register(&WEBDAVProtocolServer)

	mapping := make(map[string]func())
	mapping[SFTPProtocolServer.name] = func() { registry.Start(SFTPProtocolServer.name, &SFTPProtocolServer) }
	mapping[WEBDAVProtocolServer.name] = func() { registry.Start(WEBDAVProtocolServer.name, &WEBDAVProtocolServer) }

	log.Println("protocol: enabled protocols = ", cfg.ProtocolConfig.ProtocolsEnabled)
	for _, val := range cfg.ProtocolConfig.ProtocolsEnabled {
		if fn, ok := mapping[val]; ok {
			log.Println("protocol: enabling ", val)
			fn()
		}
	}

}
